# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dask-scheduler
  namespace: regrid
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      serviceAccountName: dask-autoscaler
      automountServiceAccountToken: true
      containers:
        - image: informaticslab/regridding_processor:kubenetes
          command: ["sh", "-c"]
          args:
            - dask-scheduler --port 8786 --bokeh-port 8787
          imagePullPolicy: Always
          name: dask-scheduler
          ports:
            - containerPort: 8787
            - containerPort: 8786
          resources:
            requests:
              cpu: 100m
              memory: 1Gi # Do we need to grab this much?
---
# Service
kind: Service
metadata:
  name: dask
  namespace: regrid
spec:
  ports:
    - port: 8786
      targetPort: 8786
      protocol: TCP
  selector:
    app: dask-scheduler
---
# Service
kind: Service
metadata:
  name: dask-stats
  namespace: regrid
spec:
  ports:
    - port: 80
      targetPort: 8787
      protocol: TCP
  selector:
    app: dask-scheduler
---
# ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: regrid-stats.informaticslab.co.uk
  namespace: regrid
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - regrid-stats.informaticslab.co.uk
    secretName: regrid-stats-api-tls
  rules:
  - host: regrid-stats.informaticslab.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: dask-stats
          servicePort: 80